
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Quaternary structure
typedef struct { char op[16]; char arg1[32]; char arg2[32]; char result[32]; } Quad;
Quad ir_codes[10000];
int ir_ptr = 0;
int temp_counter = 1;

char* new_temp() {
    char* t = (char*)malloc(16);
    sprintf(t, "t%d", temp_counter++);
    return t;
}

int nextinstr() { return ir_ptr; }

void emit(const char* op, const char* arg1, const char* arg2, const char* result) {
    strcpy(ir_codes[ir_ptr].op, op);
    strcpy(ir_codes[ir_ptr].arg1, arg1);
    strcpy(ir_codes[ir_ptr].arg2, arg2);
    strcpy(ir_codes[ir_ptr].result, result);
    ir_ptr++;
}

// Linked list structure is used for --backpatch--
typedef struct IntNode { int val; struct IntNode* next; } IntNode;
typedef struct { IntNode* head; IntNode* tail; } IntList;

IntList* makelist(int index) {
    IntList* list = (IntList*)malloc(sizeof(IntList));
    IntNode* node = (IntNode*)malloc(sizeof(IntNode));
    node->val = index; node->next = NULL;
    list->head = list->tail = node;
    return list;
}

IntList* merge_list(IntList* p1, IntList* p2) {
    if (!p1 || !p1->head) return p2;
    if (!p2 || !p2->head) return p1;
    p1->tail->next = p2->head;
    p1->tail = p2->tail;
    return p1;
}

void backpatch(IntList* list, int target_instr) {
    if (!list) return;
    char buf[32]; sprintf(buf, "%d", target_instr);
    IntNode* curr = list->head;
    while (curr) {
        strcpy(ir_codes[curr->val].result, buf);
        curr = curr->next;
    }
}

typedef struct { IntList* truelist; IntList* falselist; } CondOut;

void print_ir() {
    for (int i = 0; i < ir_ptr; i++) {
        Quad q = ir_codes[i];
        printf("%d:\t", i);
        if (q.op[0] == 'j') {
            if (strcmp(q.op, "j") == 0) printf("goto %s\n", q.result);
            else printf("if %s %s %s goto %s\n", q.arg1, q.op + 1, q.arg2, q.result);
        } else if (strcmp(q.op, "LABEL") == 0) {
            printf("%s:\n", q.arg1);
        } else if (strcmp(q.op, "RET") == 0) {
            printf("return %s\n", q.arg1);
        } else if (strcmp(q.op, "=") == 0) {
            printf("%s = %s\n", q.result, q.arg1);
        } else if (strcmp(q.op, "call") == 0) {
            printf("%s = call %s\n", q.result, q.arg1);
        } else {
            printf("%s = %s %s %s\n", q.result, q.arg1, q.op, q.arg2);
        }
    }
}

int main() {
    char* v0 = new_temp();
    emit("*", "c", "2", v0);
    char* v1 = new_temp();
    emit("+", "b", v0, v1);
    emit("=", v1, "", "a");
    // Generate -IF- zipper backfill logic
    CondOut v2;
    v2.truelist = makelist(nextinstr());
    v2.falselist = makelist(nextinstr() + 1);
    emit("j<", "a", "100", "_");
    emit("j", "", "", "_");
    int v3 = nextinstr();
    backpatch(v2.truelist, v3);
    char* v4 = new_temp();
    emit("+", "a", "1", v4);
    emit("=", v4, "", "a");
    IntList* v5 = makelist(nextinstr());
    emit("j", "", "", "_");
    int v6 = nextinstr();
    backpatch(v2.falselist, v6);
    char* v7 = new_temp();
    emit("-", "a", "1", v7);
    emit("=", v7, "", "a");
    backpatch(v5, nextinstr());
    // Generate -WHILE- zipper backfill logic
    int v8 = nextinstr();
    CondOut v9;
    v9.truelist = makelist(nextinstr());
    v9.falselist = makelist(nextinstr() + 1);
    emit("j>", "b", "0", "_");
    emit("j", "", "", "_");
    int v10 = nextinstr();
    backpatch(v9.truelist, v10);
    char* v11 = new_temp();
    emit("-", "b", "1", v11);
    emit("=", v11, "", "b");
    char buf_v8[16]; sprintf(buf_v8, "%d", v8);
    emit("j", "", "", buf_v8);
    backpatch(v9.falselist, nextinstr());
    printf("\n=== Three-address code generated by meta-compilation (Meta-Compilation) ===\n");
    print_ir();
    return 0;
}
