/**
 * code_generator.cpp - Generate lex.yy.c from a minimized DFA
 *
 * The output file contains a complete, self-contained C lexical analyser
 * that implements a table-driven DFA with longest-match and backtracking.
 */
#include "code_generator.h"
#include <fstream>
#include <iomanip>

/* Escape a string for embedding in C source as a string literal */
static std::string c_escape(const std::string& s) {
    std::string out;
    for (char c : s) {
        switch (c) {
            case '\\': out += "\\\\"; break;
            case '"':  out += "\\\""; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default: out += c; break;
        }
    }
    return out;
}

/* Strip outer braces from an action string (if present):  "{ code }" -> " code " */
static std::string strip_braces(const std::string& s) {
    std::string t = s;
    /* Trim leading/trailing whitespace */
    size_t start = t.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    size_t end = t.find_last_not_of(" \t\r\n");
    t = t.substr(start, end - start + 1);

    if (t.size() >= 2 && t.front() == '{' && t.back() == '}') {
        return t.substr(1, t.size() - 2);
    }
    return t;
}

void generate_lex_yy_c(
    const std::string& output_path,
    const DFA& dfa,
    const LexFile& lf)
{
    std::ofstream out(output_path);
    if (!out.is_open()) {
        std::cerr << "Error: cannot open output file '" << output_path << "'" << std::endl;
        exit(1);
    }

    int num_states = (int)dfa.states.size();
    int dead_state = num_states; /* virtual dead/error state (one past real states) */

    /* ===== Header ===== */
    out << "/* lex.yy.c - Generated by SeuLex */\n";
    out << "#include <stdio.h>\n";
    out << "#include <stdlib.h>\n";
    out << "#include <string.h>\n\n";

    /* ===== User preamble code ===== */
    if (!lf.definition_code.empty()) {
        out << "/* === User preamble code (from %%{ ... %%}) === */\n";
        out << lf.definition_code << "\n";
    }

    /* ===== Global variables ===== */
    out << "/* === Lexer globals === */\n";
    out << "FILE *yyin = NULL;\n";
    out << "FILE *yyout = NULL;\n";
    out << "#define YY_BUF_SIZE 16384\n";
    out << "static char yy_buf[YY_BUF_SIZE];\n";
    out << "static int  yy_buf_pos = 0;\n";
    out << "static int  yy_buf_len = 0;\n\n";
    out << "char yytext[YY_BUF_SIZE];\n";
    out << "int  yyleng = 0;\n\n";

    /* ===== input() / unput() ===== */
    out << "static int input(void) {\n";
    out << "    if (yy_buf_pos < yy_buf_len) return (unsigned char)yy_buf[yy_buf_pos++];\n";
    out << "    if (!yyin) yyin = stdin;\n";
    out << "    yy_buf_len = (int)fread(yy_buf, 1, YY_BUF_SIZE, yyin);\n";
    out << "    yy_buf_pos = 0;\n";
    out << "    if (yy_buf_len <= 0) return 0; /* Flex-compatible EOF sentinel */\n";
    out << "    return (unsigned char)yy_buf[yy_buf_pos++];\n";
    out << "}\n\n";
    out << "static void unput_n(int n) {\n";
    out << "    yy_buf_pos -= n;\n";
    out << "    if (yy_buf_pos < 0) yy_buf_pos = 0;\n";
    out << "}\n\n";

    /* ===== Transition table ===== */
    out << "/* === DFA transition table === */\n";
    out << "/* transition_table[state][char] = next_state, " << dead_state << " = dead */\n";
    out << "#define YY_NUM_STATES " << num_states << "\n";
    out << "#define YY_DEAD_STATE " << dead_state << "\n";
    out << "#define YY_START_STATE " << dfa.start_state << "\n\n";
    out << "static const int yy_transition[" << num_states << "][256] = {\n";

    for (int i = 0; i < num_states; i++) {
        out << "    {";
        for (int ch = 0; ch < 256; ch++) {
            auto it = dfa.states[i].transitions.find(ch);
            int target = (it != dfa.states[i].transitions.end()) ? it->second : dead_state;
            out << target;
            if (ch < 255) out << ",";
        }
        out << "}";
        if (i < num_states - 1) out << ",";
        out << "\n";
    }
    out << "};\n\n";

    /* ===== Accept table ===== */
    out << "/* Accept table: yy_accept[state] = rule_index, -1 = not accept */\n";
    out << "static const int yy_accept[" << num_states << "] = {";
    for (int i = 0; i < num_states; i++) {
        if (i > 0) out << ",";
        out << (dfa.states[i].is_accept ? dfa.states[i].rule_index : -1);
    }
    out << "};\n\n";

    /* ===== yylex() ===== */
    out << "int yylex(void) {\n";
    out << "yy_start:\n";
    out << "    {\n";
    out << "        int yy_state = YY_START_STATE;\n";
    out << "        int yy_last_accept_state = -1;\n";
    out << "        int yy_last_accept_len = 0;\n";
    out << "        yyleng = 0;\n";
    out << "\n";
    out << "        while (1) {\n";
    out << "            int c = input();\n";
    out << "            if (c == 0) {\n";
    out << "                /* EOF */\n";
    out << "                if (yy_last_accept_state >= 0) break;\n";
    out << "                return 0;\n";
    out << "            }\n";
    out << "\n";
    out << "            int yy_next = yy_transition[yy_state][(unsigned char)c];\n";
    out << "            if (yy_next == YY_DEAD_STATE) {\n";
    out << "                /* No transition: backtrack */\n";
    out << "                unput_n(1); /* unput the char that caused failure */\n";
    out << "                break;\n";
    out << "            }\n";
    out << "\n";
    out << "            if (yyleng >= YY_BUF_SIZE - 1) {\n";
    out << "                yytext[YY_BUF_SIZE - 1] = '\\0';\n";
    out << "                fprintf(stderr, \"[SeuLex] token too long, truncated\\n\");\n";
    out << "                return 0;\n";
    out << "            }\n";
    out << "\n";
    out << "            yytext[yyleng++] = (char)c;\n";
    out << "            yy_state = yy_next;\n";
    out << "\n";
    out << "            if (yy_accept[yy_state] >= 0) {\n";
    out << "                yy_last_accept_state = yy_state;\n";
    out << "                yy_last_accept_len = yyleng;\n";
    out << "            }\n";
    out << "        }\n";
    out << "\n";
    out << "        /* Backtrack to last accept position */\n";
    out << "        if (yy_last_accept_state >= 0) {\n";
    out << "            int rollback = yyleng - yy_last_accept_len;\n";
    out << "            if (rollback > 0) unput_n(rollback);\n";
    out << "            yyleng = yy_last_accept_len;\n";
    out << "            yytext[yyleng] = '\\0';\n";
    out << "\n";
    out << "            switch (yy_accept[yy_last_accept_state]) {\n";

    /* Generate case for each rule */
    for (size_t i = 0; i < lf.rules.size(); i++) {
        const LexRule& rule = lf.rules[i];
        std::string action = strip_braces(rule.action);

        /* Trim the action */
        std::string trimmed = action;
        size_t s1 = trimmed.find_first_not_of(" \t\r\n");
        if (s1 != std::string::npos) trimmed = trimmed.substr(s1);
        size_t s2 = trimmed.find_last_not_of(" \t\r\n");
        if (s2 != std::string::npos) trimmed = trimmed.substr(0, s2 + 1);

        out << "            case " << rule.rule_index << ": /* "
            << c_escape(rule.pattern) << " */\n";
        out << "                {" << action << "}\n";
        out << "                goto yy_start;\n";
    }

    out << "            default:\n";
    out << "                goto yy_start;\n";
    out << "            }\n";
    out << "        }\n";
    out << "\n";
    out << "        /* No match at all: consume one char and try again */\n";
    out << "        if (yyleng == 0) {\n";
    out << "            int c = input();\n";
    out << "            if (c == 0) return 0;\n";
    out << "            /* ECHO */\n";
    out << "            if (!yyout) yyout = stdout;\n";
    out << "            fputc(c, yyout);\n";
    out << "            goto yy_start;\n";
    out << "        }\n";
    out << "    }\n";
    out << "    return 0;\n";
    out << "}\n\n";

    /* ===== User subroutine section ===== */
    if (!lf.user_code.empty()) {
        out << "/* === User subroutine section === */\n";
        out << lf.user_code << "\n";
    }

    /* ===== Default main (if not provided) ===== */
    /* We don't generate main() since user_code typically provides it,
       or this will be linked with yacc which has main(). */

    out.close();
    std::cerr << "[SeuLex] Generated " << output_path << " (" << num_states << " DFA states)" << std::endl;
}
